config/routes.rb
Rails.application.routes.draw do

root 'welcome#index'
resources :industries
resources :companies

end

app/models/company.rb
class Company < ActiveRecord::Base

has_and_belongs_to_many :industries

validates :name, :description, :price, presence: true

end

app/models/industry.rb
class Industry < ActiveRecord::Base

has_and_belongs_to_many :companies

validates :name, :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
def index
  @companies = Company.all
end

def new
  @company = Company.new
  @industry = Industry.find_by_id(params[:industry_id])
  @industries = Industry.all
end

def create
  @industry = Industry.find_by_id(params[:industry_id])
  @company = Company.new(company_params)
  @company.industries << @industry
  if @company.save
    flash[:notice] = "COMPANY WAS CREATED SUCCESSFULLY."
    redirect_to company_path(@company)
  else
    render :new
  end
end

def show
  @company = Company.find(params[:id])
  @industry = Industry.find_by_id(params[:industry_id])
end

def edit
  @industry = Industry.find_by_id(params[:industry_id])
  @company = Company.find(params[:id])
end

def update
  @industry = Industry.find_by_id(params[:industry_id])
  @company = Company.find(params[:id])
  @industries = Industry.all
  @company.industries << @industry
  if @company.update(company_params)
    flash[:notice] = "COMPANY WAS UPDATED SUCCESSFULLY."
    redirect_to companies_path
  else
    render 'edit'
  end
end

def destroy
  @company = Company.find(params[:id])
  @company.destroy
  redirect_to companies_path
  flash[:notice] = "COMPANY WAS DELETED."
end


private
def company_params
  params.require(:company).permit(:name, :description, :price)
end

end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
def index
  @industries = Industry.all
  @companies = Company.all
  @company = Company.find_by_id(params[:company_id])
end

def new
  @industry = Industry.new
end

def create
  @company = Company.find_by_id(params[:company_id])
  @industry = Industry.new(industry_params)
  @industry.id
  if @industry.save
    flash[:notice] = "INDUSTRY WAS CREATED SUCCESSFULLY."
    redirect_to industry_path(@industry)
  else
    render :new
  end
end

def show
  @company = Company.find_by_id(params[:company_id])
  @industry = Industry.find(params[:id])
end

def edit
  @industry = Industry.find(params[:id])
end

def update
  @company = Company.find_by_id(params[:company_id])
  @industry = Industry.find(params[:id])
  if @industry.update(industry_params)
    flash[:notice] = "INDUSTRY WAS UPDATED SUCCESSFULLY."
    redirect_to industries_path
  else
    render 'edit'
  end
end

def destroy
  @industry = Industry.find(params[:id])
  @industry.destroy
  redirect_to industries_path
  flash[:notice] = "INDUSTRY WAS DELETED."
end



private
def industry_params
  params.require(:industry).permit(:name, :description)
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/edit.html.erb
<h1> Edit Company </h1>

<hr>

<% if @company.errors.any? %>
<h2><%= pluralize(@company.errors.count, "error") %> prohibited this entry from being saved:</h2>

<ul>
  <% @company.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>



<%= form_for @company do |f| %>

  <%= f.label :industry_id, 'Industries' %>
  <%= collection_select @industry, :industry_id, Industry.all, :id, :name, :prompt => 'Select Industry', :multiple => true %>

  <br>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <br>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <br>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.submit 'Update' %>
  <% end %>

app/views/companies/index.html.erb
<h1>  ALL THE COMPANIES EVER CREATED! </h1>
<%= link_to 'Add a New Company', new_company_path %>

<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

<hr>

<table>
  <tr>
    <th>
      Company Name
    </th>
    <th>
      Price
    </th>
    <th>
      Created At
    </th>
    <th>

    </th>
    <th>
      Updated At
    </th>
  </tr>

  <% @companies.each do |company| %>
  <tr>
    <th>
      <%= link_to company.name, company_path(company) %>
    </th>
    <th>
      <%= company.price %>
    </th>
    <th>
      <%= company.created_at.strftime "%m-%d-%Y  %H:%M:%S" %>
    </th>
    <th>

    </th>
    <th>
      <%= company.updated_at.strftime "%m-%d-%Y  %H:%M:%S" %>
    </th>
  </tr>
  <% end %>
</table>

app/views/companies/new.html.erb
<h1> Create a new company </h1>

<hr>

<% if @company.errors.any? %>
<h2><%= pluralize(@company.errors.count, "error") %> prohibited this entry from being saved:</h2>

<ul>
  <% @company.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>


<%= form_for @company do |f| %>

  <%= f.label :industry_id, 'Industries' %>
  <%= collection_select @industry, :industry_id, Industry.all, :id, :name, :prompt => 'Select Industry', :multiple => true %>

  <br>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <br>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <br>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.submit 'Create' %>
  <% end %>

app/views/companies/show.html.erb
<h1> COMPANY SHOW PAGE </h2>

  <%= link_to 'Edit Company', edit_company_path(@company) %>
  <%= link_to("Delete Company", @company, :method => :delete, :class => 'action', data: {confirm: "Are you sure?"}) %>

  <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>

<hr>

<em><h2> About </h2></em>
<strong> <h3> Name: </h3> </strong> <%= @company.name %>
<strong> <h3> Description: </h3> </strong> <%= @company.description %>
<strong> <h3> Price: </h3> </strong> <%= @company.price %>
<strong> <h3> Date/Time Created: </h3> </strong> <%= @company.created_at.strftime "%m-%d-%Y  %H:%M:%S" %>
<strong> <h3> Date/Time Last Updated: </h3> </strong> <%= @company.updated_at.strftime "%m-%d-%Y  %H:%M:%S" %>

<em><h2> Industries That This Company is a Part Of </h2></em>

<table>
  <tr>
    <th>
      Industry Name
    </th>
    <th>
    </th>
    <th>
      Description
    </th>
    <th>
    </th>
  </tr>

<% @company.industries.each do |industry| %>
  <tr>
    <td>
      <%= industry.name %>
    </td>
    <td>
    </td>
    <td>
      <%= industry.description %>
    </td>
  </tr>
  <% end %>
</table>

app/views/industries/edit.html.erb
<h1> Edit Industry </h1>

<hr>

<%= form_for @industry do |f| %>

<br>

<%= f.label :name %>
<%= f.text_field :name %>

<br>

<%= f.label :description %>
<%= f.text_area :description %>

<br>



<%= f.submit 'Update' %>
<% end %>

app/views/industries/index.html.erb
<h1> ALL INDUSTRIES OUT THERE!!  </h1>
<%= link_to 'Add a New Industry', new_industry_path %>

<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

<hr>

<table>
  <tr>
    <th>
      Industry Name
    </th>
    <th>
      Created At
    </th>
    <th>
      Updated At
    </th>
  </tr>


  <% @industries.each do |industry| %>
  <tr>
    <td>
      <%= link_to industry.name, industry_path(industry) %>
    </td>
    <td>
      <%= industry.created_at.strftime "%m-%d-%Y  %H:%M:%S" %>
    </td>
    <td>
      <%= industry.updated_at.strftime "%m-%d-%Y  %H:%M:%S" %>
    </td>
  </tr>

  <% industry.companies.each do |company| %>
  <tr>
    <td>
      Company: <%= company.name %>
    </td>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/industries/new.html.erb
<h1> Create a new industry </h1>

<hr>

<%= form_for @industry do |f| %>

<br>

<%= f.label :name %>
<%= f.text_field :name %>

<br>

<%= f.label :description %>
<%= f.text_area :description %>

<br>

<%= f.submit 'Create' %>
<% end %>

app/views/industries/show.html.erb
<h1> INDUSTRY SHOW PAGE </h1>

<%= link_to 'Edit Industry', edit_industry_path(@industry) %>
<%= link_to("Delete Industry", @industry, :method => :delete, :class => 'action', data: {confirm: "Are you sure?"}) %>

<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

<hr>

<em><h2> About </h2></em>

<strong> <h3> Name: </h3> </strong>
<%= @industry.name %>

<strong> <h3> Description: </h3> </strong>
<%= @industry.description %>

<strong> <h3> Date/Time Created: </h3> </strong>
<%= @industry.created_at.strftime "%m-%d-%Y   %H:%M:%S" %>

<strong> <h3> Date/Time Last Updated: </h3> </strong>
<%= @industry.updated_at.strftime "%m-%d-%Y   %H:%M:%S" %>

<em><h2> Companies in This Industry </h2></em>

<table>
  <tr>
    <th>
      Co. Name
    </th>
    <th>

    </th>
    <th>
      Co. Description
    </th>
    <th>
      Co. Price
    </th>
  </tr>


  <% @industry.companies.each do |company| %>
  <tr>
    <td>
      <%= company.name %>
    </td>
    <td>

    </td>
    <td>
      <%= company.description %>
    </td>
    <td>
      <%= company.price %>
    </td>
  </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assess2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<%= link_to 'Industries Index', industries_path %>

<br>

<%= link_to 'Companies Index',companies_path %>